project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - courses/SSR/2022-2023/index.qmd
    - courses/SSR/2022-2023/nhst/nhst.qmd
    - courses/WSR_PB/2022-2023/index.qmd
    - courses/WSR_PB/2022-2023/nhst/nhst.qmd

website:
  title: "Statistics Lectures"
  site-url: https://shklinkenberg.github.io
  repo-url: https://github.com/ShKlinkenberg/statistics-lectures
  repo-actions: [edit, issue]
  google-analytics: "UA-107432294-1"
  page-navigation: true
  navbar:
    left:
      - text: Courses
        menu: 
          - sidebar:SSR
          - sidebar:WSR

    right:
      - icon: github
        href: https://github.com/ShKlinkenberg/statistics-lectures
        aria-label: Quarto GitHub

  sidebar:
    - id: SSR
      title: "Scientific & Statistical Reasoning"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - courses/SSR/2022-2023/index.qmd
        - courses/SSR/2022-2023/nhst/nhst.qmd
    - id: WSR
      title: "Wetenschapsfilosofie & Statistisch Redeneren"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - courses/WSR_PB/2022-2023/index.qmd
        - courses/WSR_PB/2022-2023/nhst/nhst.qmd

format:
  html:
    theme: cosmo
    toc: true
    df-print: kable
    smooth-scroll: true
    link-external-newwindow: true

freeze: false