# project:
#   output-dir: ../docs/courses/2022-2023_SSR/
author: "Sharon Klinkenberg"
institute: "University of Amsterdam"
format:
  revealjs:
    smaller: false
    linkcolor: '#BC0031'
    logo: https://shklinkenberg.github.io/uva_style/images/logo_uva.png
    transition: slide
    background-transition: fade
    theme: white
    slide-number: true
    css: uva_reveal.css
    footer: "@ShKlinkenberg"
    title-slide-attributes:
      data-background-image: https://shklinkenberg.github.io/uva_style/images/uva_bg.jpg
      data-background-size: contain
      data-background-position: bottom